language: python
arch:
   - amd64
   - ppc64le
sudo: false
dist: xenial
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy
    - pypy3

install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U flake8
    - pip install -U pygments
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=.
    - flake8 setup.py ZConfig
notifications:
    email: false
after_success:
    - coveralls

cache: pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
